version: "3.8"
services:
    kafka:
        image: confluentinc/cp-kafka:7.8.3
        container_name: kafka
        ports: 
            - 9092:9092

        environment:
            CLUSTER_ID: 'k3zXzjNqOiYxYJv-kXO6nQ'
            KAFKA_NODE_ID: 1

            KAFKA_PROCESS_ROLES: broker, controller
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
 
            KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092, INTERNAL://0.0.0.0:29092, CONTROLLER://0.0.0.0:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT, CONTROLLER:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092, INTERNAL://kafka:29092
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

            KAFKA_LOG_DIRS: /tmp/kraft-combined_logs

        volumes: 
            - kafka_kraft:/var/lib/kafka/data

    kafka-ui:
        container_name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports: 
            - 8080:8080
        depends_on:
            - kafka
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

volumes:
    kafka_kraft: